# Generated by Django 2.0.5 on 2019-01-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'blog列表'},
        ),
        migrations.AlterModelTable(
            name='blogarticles',
            table='blog_list',
        ),
    ]
